
version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wijnfestijnDB
      PGDATA: /data/postgres
    volumes:
       - /data/postgres:/data/postgres
       - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
